name: Run Postman Collection
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Run collection
        run: newman run collection.json -e environment.json --reporters cli,html --reporter-html-export report.html
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: report.html
